services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - auth_service/.env
    depends_on:
      - ms-auth
    restart: always

  db-auth:
    image: postgres:latest
    container_name: db-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_own_password_123
      POSTGRES_DB: auth_users
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ms-auth:
    container_name: ms-auth
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - auth_service/.env
    depends_on:
      - db-auth
    restart: always

  db-profiles:
    image: postgres:latest
    container_name: db-profiles
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_own_password_123
      POSTGRES_DB: users_profiles
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data_auth:
    driver: local