services:
#  api-gateway:
#    container_name: api-gateway
#    build:
#      context: .\api-gateway
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8000"
#    environment:
#      - ENV=dev
##    depends_on:
##      - ms-auth
#    restart: always

  db-pgsql:
    image: postgres:latest
    container_name: db-pgsql-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_own_password_123
      POSTGRES_DB: auth_users
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ms-auth:
    container_name: ms-auth
    build:
      context: .\auth_service
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./auth_service/keys:/app/keys:ro
    env_file:
      - auth_service/.env
    depends_on:
      - db-pgsql
    restart: always
volumes:
  postgres_data_auth:
    driver: local